import { expect, test } from '@playwright/test'

test('operator runs a snapshot-bound mission with exclusive authority and latched EStop', async ({ page }) => {
  const token = process.env.EMBODIED_OPERATOR_TOKEN
  expect(token?.length).toBeGreaterThanOrEqual(32)
  await page.goto('/')
  const board = page.getByRole('region', { name: 'Control board supervisado' })
  await expect(board.getByRole('status', { name: 'Estado del supervisor' })).toContainText('Disarmed')
  await expect(board.getByRole('button', { name: 'Proponer plan' })).toBeDisabled()
  await board.getByLabel('Token de operador local').fill(token!)
  await board.getByLabel('Identificador del operador').fill('playwright-operator')
  await board.getByRole('button', { name: 'Tomar lease' }).click()
  await expect(board.getByText(/Lease temporal activa/)).toBeVisible()
  await board.getByRole('button', { name: 'Proponer plan' }).click()
  await expect(board.getByText(/Estado: proposed/)).toBeVisible()
  await board.getByRole('checkbox', { name: /Confirmo que revisé/ }).check()
  await board.getByRole('button', { name: 'Manual', exact: true }).click()
  await expect(board.getByRole('status', { name: 'Estado del supervisor' })).toContainText('Manual')
  await board.getByRole('button', { name: 'Aprobar' }).click()
  await expect(board.getByText(/Estado: approved/)).toBeVisible()
  await board.getByRole('button', { name: 'Ejecutar' }).click()
  await expect(board.getByText(/Estado: completed/)).toBeVisible({ timeout: 20_000 })
  await expect(board.getByText('Feedback ROS correlacionado')).toBeVisible()
  await expect(board.locator('.control-signal')).toContainText('error')
  await board.getByRole('button', { name: 'E‑Stop simulado' }).click()
  await expect(board.getByRole('status', { name: 'Estado del supervisor' })).toContainText('E-STOP ENCLAVADO')
  await board.getByRole('button', { name: 'Reset · permanece Disarmed' }).click()
  await expect(board.getByRole('status', { name: 'Estado del supervisor' })).toContainText('Disarmed')
  await expect(board.getByRole('status', { name: 'Estado del supervisor' })).not.toContainText('ENCLAVADO')
})

test('replay never enables operator controls', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('status', { name: 'Estado de la simulación' })).toContainText('LIVE SIMULATION', { timeout: 20_000 })
  await page.getByRole('button', { name: 'Cargar replay' }).click()
  const board = page.getByRole('region', { name: 'Control board supervisado' })
  await expect(board).toContainText('REPLAY: CONTROL BLOQUEADO')
  await expect(board.getByRole('button', { name: 'Proponer plan' })).toBeDisabled()
  await expect(board.getByRole('button', { name: 'E‑Stop simulado' })).toBeDisabled()
})
